Sandstorm:
  ConfigLoader:
    externalConfig:
      'File':
        source: Sandstorm\ConfigLoader\Source\FileSource
        sourceOptions:
          path: '/Users/bastian/Downloads/test.txt'
      'Env':
        source: Sandstorm\ConfigLoader\Source\EnvSource
        sourceOptions:
          name: 'VCAP_SERVICES'
      'Raw':
        source: Sandstorm\ConfigLoader\Source\RawSource
        sourceOptions:
          value: '{"foo":"bar"}'
        transformation: Sandstorm\ConfigLoader\Transformation\JsonTransformation

Neos:
  Flow:
    persistence:
      backendOptions:
        dbName: '%EXT:Raw.mariadbent.credentials.database%'
